name: skip_the_chase
description: A dating app that allows users to check in to venues and find dates around them.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  supabase_flutter: ^2.9.1
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  timeago: ^3.6.0
  intl: ^0.18.1
  uuid: ^4.2.1
  cached_network_image: ^3.3.0
  flutter_card_swiper: ^6.0.0
  sign_in_with_apple: ^7.0.1
  postgrest: 2.4.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/